version: "3.0"
services:

  api:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=apigw
    image: wareed/enhanced-example-api-service
    ports:
      - "80:80"
      - "9090:9090"
    links:
      - users
      - orders

  users:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=users
    image: wareed/enhanced-example-users-service

  orders:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - image_name=orders
    image: wareed/enhanced-example-orders-service
